1 module: 2-task and 3-task
js-tasks-ru/jsbasic-20221114_verstku pull request #3
Opened 2022-11-24 14:34 UTC by verstku

Created a functions: isValid(name) and isFirst(str)

2022-11-24 14:35 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-11-24 17:27 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-11-24 17:32 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2022-11-24 18:01 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2022-11-25 09:22 UTC, SinimaWath requested changes

2022-11-25 09:22 UTC, SinimaWath commented on 1-module/2-task/index.js
> +  return false;
- если результат операции boolean, то if не нужен: `return name && name.length > 3 && !name.match(/\s/g)`
- `!name.match(/\s/g)` - проще заменить на `!name.includes(' ')`

2022-11-25 09:22 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  return false
`return str.indexOf('xxx') != -1 || str.indexOf('1xbet') != -1`

2022-11-25 13:03 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-11-27 10:10 UTC, SinimaWath approved these changes

2022-11-27 10:10 UTC, merged