4-module
js-tasks-ru/jsbasic-20221114_verstku pull request #6
Opened 2022-12-09 12:24 UTC by verstku

2022-12-09 12:24 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-12-09 15:56 UTC, SinimaWath requested changes

2022-12-09 15:56 UTC, SinimaWath commented on 4-module/2-task/index.js
> +  for (let tableRow of table.rows) {
Если нужен index, то использовать циклю for of - не имеет смысла.

Тут стоит применить: `for (let index = 0; index < table.rows.length; index += 1)`

2022-12-09 16:58 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-12-10 17:10 UTC, SinimaWath approved these changes

2022-12-10 17:10 UTC, merged